# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    refresh:
      enable: false

#server:
  # 0으로 세팅하면 spring이 임의 port를 할당(굳이 8081..등으로 관리할 필요없음)
  # eureka에 등록할 때 할당된 임의 port를 알려주면 apigate가 ureka에게 물어보므로 개발자가 port를 관리할 필요가 없다
  # github에 올리고, busrefresh 사용할 땐, server:port: 없애 주고, member,ordering,product 포트 번호 지정해줘야 에러 안남
  #port: 0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
